export const REGIONS = {
	BayArea: { name: 'San Francisco Bay Area / Northern California', timezone: 'PT' },
	LosAngeles: { name: 'Los Angeles / Southern California', timezone: 'PT' },
	Seattle: { name: 'Seattle', timezone: 'PT' },
	Atlanta: { name: 'Atlanta', timezone: 'ET' },
	Miami: { name: 'Miami', timezone: 'ET' },
	DC: { name: 'Washington, DC / Maryland / Virginia', timezone: 'ET' },
	Toronto: { name: 'Toronto', timezone: 'ET' },
	Texas: { name: 'Texas', timezone: 'MT' },
	Iowa: { name: 'Iowa / Nebraska', timezone: 'CT' },
	Denver: { name: 'Denver', timezone: 'MT' },
	CHI: { name: 'Chicago', timezone: 'CT' },
	Detroit: { name: 'Detroit', timezone: 'ET' },
	Massachusetts: { name: 'Massachusetts', timezone: 'ET' },
	LasVegas: { name: 'Las Vegas', timezone: 'PT' },
	Phoenix: { name: 'Phoenix', timezone: 'PT' },
	PNW: { name: 'PNW', timezone: 'PT' },
	ORE: { name: 'Oregon', timezone: 'PT' },
	BC: { name: 'British Columbia', timezone: 'PT' },
} as const;
